name: register-docker-image

on: [push]

env:
  APP_TAG: 1.0.0
  WEB_TAG: 1.0.0
  DB_TAG: 1.0.0
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  docker-image-register:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: doma2mo10
          password: dckr_pat_A3h_qLuO-5RDL906Tcs9mOzZzhI

      - name: Build & Push app Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/php/Dockerfile
          push: true
          platforms: linux/arm64, linux/amd64
          tags: doma2mo10/backend-app:${{ env.APP_TAG }}

      - name: push latest app Container
        run: |
          docker tag doma2mo10/backend-app:${{ env.APP_TAG }} doma2mo10/backend-app:latest
          docker push doma2mo10/backend-app:latest

      - name: Build & Push web Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/nginx/Dockerfile
          push: true
          platforms: linux/arm64, linux/amd64
          tags: doma2mo10/backend-web:${{ env.WEB_TAG }}

      - name: push latest web Container
        run: |
          docker tag doma2mo10/backend-web:${{ env.WEB_TAG }} doma2mo10/backend-web:latest
          docker push doma2mo10/backend-web:latest

      - name: Build & Push db Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/mysql/Dockerfile
          push: true
          platforms: linux/arm64, linux/amd64
          tags: doma2mo10/backend-db:${{ env.DB_TAG }}

      - name: push latest db Container
        run: |
          docker tag doma2mo10/backend-db:${{ env.DB_TAG }} doma2mo10/backend-db:latest
          docker push doma2mo10/backend-db:latest

      - name: Success
        uses: rtCamp/action-slack-notify@v2.0.2
        if: success()
        env:
          SLACK_TITLE: register docker image flow / Success
          SLACK_COLOR: good
          SLACK_MESSAGE: Message for Success

      - name: Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_TITLE: register docker image flow / Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: Message for Failure

      - name: Cancel
        uses: rtCamp/action-slack-notify@v2.0.2
        if: cancelled()
        env:
          SLACK_TITLE: register docker image flow / Cancel
          SLACK_COLOR: danger
          SLACK_MESSAGE: Message for Cancel
