name: register-docker-image

on:
  push:
    paths:
      - "infra/**"

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  docker-image-register:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push app Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/php/Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest

      - name: Build & Push nginx Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/nginx/Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-web:latest

      - name: Build & Push db Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/mysql/Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-db:latest

      - name: Success
        uses: rtCamp/action-slack-notify@v2.0.2
        if: success()
        env:
          SLACK_TITLE: CI flow / Success
          SLACK_COLOR: good
          SLACK_MESSAGE: Message for Success

      - name: Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_TITLE: CI flow / Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: Message for Failure

      - name: Cancel
        uses: rtCamp/action-slack-notify@v2.0.2
        if: cancelled()
        env:
          SLACK_TITLE: CI flow / Cancel
          SLACK_COLOR: danger
          SLACK_MESSAGE: Message for Cancel
